name: tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  auto_size_text: ^3.0.0
  card_swiper: ^3.0.1
  cloud_firestore: ^4.09.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.10.0
  firebase_core: ^2.17.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  jiffy: ^6.3.1
  location: ^6.0.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
